### ISSUE TITLE
travis and coveralls not working

### ISSUE THREAD

**Issue by stoeffel** [1-liners/module-indexer#1]
I will publish this as soon as coveralls has synced the repo
and travis works again.

Currently travis seems to have issues on iojs saw the same error on different projects today [travis-ci/issues/3992](https://github.com/travis-ci/travis-ci/issues/3992)

**Comment by stoeffel** [comment]
refs https://github.com/nodejs/io.js/issues/1850

**Comment by hemanth** [comment]
yup, noticed the same in other projects as well.
